/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mx.udg.cucea.controlDeProductos.vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import mx.udg.cucea.controlDeProductos.controlador.ControlDeProductos;
import mx.udg.cucea.controlDeProductos.modelo.Producto;

public class VentanaPrincipal extends JFrame {

    private JList lista;
    private DefaultListModel<Producto> modeloDeDatos;
    private JButton botonAgregar;
    private JButton botonEditar;
    private JButton botonBorrar;

    public VentanaPrincipal() {
        setLayout(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        inicializarComponentes();
        setSize(1200, 800);
        setVisible(true);
    }

    public void refrescarLista() {
        modeloDeDatos.clear();
        ArrayList<Producto> productos = ControlDeProductos.leerProductos();
        //modeloDeDatos.addAll(productos);
        for (Producto p : productos) {
            modeloDeDatos.addElement(p);
        }
    }

    private void inicializarComponentes() {
        lista = new JList();
        modeloDeDatos = new DefaultListModel<>();
        lista.setModel(modeloDeDatos);
        refrescarLista();
        lista.setBounds(100, 100, 500, 550);
        add(lista);

        botonAgregar = new JButton("Agregar ...");
        botonAgregar.setBounds(700, 150, 300, 100);
        botonAgregar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new VentanaProducto(VentanaPrincipal.this);
                setVisible(false);
            }
        });
        add(botonAgregar);

        botonEditar = new JButton("Editar ...");
        botonEditar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Producto productoSeleccionado = (Producto) lista.getSelectedValue();
                if (productoSeleccionado != null) {
                    new VentanaProducto(VentanaPrincipal.this, productoSeleccionado);
                    setVisible(false);
                }
            }
        });
        botonEditar.setBounds(700, 300, 300, 100);
        add(botonEditar);

        botonBorrar = new JButton("Borrar");
        botonBorrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Producto productoSeleccionado = (Producto) lista.getSelectedValue();
                if (productoSeleccionado != null) {
                    ControlDeProductos.borrarProducto(productoSeleccionado);
                    refrescarLista();
                }
            }
        });
        botonBorrar.setBounds(700, 450, 300, 100);
        add(botonBorrar);

    }
}
